# makefile.darwin - your system-specific makefile for PSRPOP
BIN = /Users/sbates/Documents/Physics/Pulsars/code/Python/pypop/fortran
FFLAGS = -O3
LDFLAGS = -L/usr/local/lib
LINK.f=f77 $(FFLAGS) $(LDFLAGS)
# The following may need to be edited by hand...
LPGPLOT = -lpgplot -lcpgplot -L/usr/X11R6/lib -lX11
