c==============================================================================
       program RLZP
c==============================================================================
c
c      produces binned data of R, L, Z and P from population files
c
c==============================================================================
       implicit none
       integer i,lun,nrbins,col,npbins,nlbins,nzbins
       real r,nr(99),rmin,rmax,nmax,delta,logl,lmin,lmax,nl(99)
       real ldeg,bdeg,ppsr,width,dmp,tau,freq,zmin,zmax,nz(99),logp,
     &        area,pi,tsky,dtrue,dderi,lpsr,s,si,x,y,z,pmin,pmax,np(99)
       integer narg,iargc,lpop,lcline,ngen,nfreq,nused
       parameter(pi=3.1415927)
       character*80 filename,cline*240

       call getarg(1,filename)
       if (filename.eq.' ') stop 'usage: rlzp popfile'
       nused=0
       lun=10
       call getmodelranges("rdist.dat",lun,rmin,rmax,nrbins)
       call getmodelranges("ldist.dat",lun,lmin,lmax,nlbins)
       call getmodelranges("zdist.dat",lun,zmin,zmax,nzbins)
       call getmodelranges("pdist.dat",lun,pmin,pmax,npbins)
       do i=1,99
          nr(i)=0.0
          nl(i)=0.0
          nz(i)=0.0
          np(i)=0.0
       enddo
       zmin=0.0
       zmax=1.0
       nzbins=20
c
c     Read the sources generated by psrdist in from disk
c
      lpop=30
      open(lpop,file=filename,form="unformatted")
      read(lpop) lcline,cline
      read(lpop) ngen,freq
      write(*,*) ngen,' in model galaxy'
      do i=1,ngen
         read(lpop) ldeg,bdeg,ppsr,width,dmp,tau,
     &                tsky,dtrue,dderi,lpsr,s,si
         lpsr=s*dtrue*dtrue
         if (lpsr.gt.0.0) then
            nused=nused+1
            call calc_xyz(ldeg,bdeg,dtrue,x,y,z)
            r=sqrt(x*x+y*y)
            z=abs(z)
            call bindata(r,rmin,rmax,nrbins,nr)
            call bindata(z,zmin,zmax,nzbins,nz)
            logl=log10(lpsr)
            call bindata(logl,lmin,lmax,nlbins,nl)
            logp=log10(ppsr)
            call bindata(logp,pmin,pmax,npbins,np)
         endif
      enddo
      close(lpop)
      write(*,*) nused,' above lmin'
      open(lpop+1,file='R',status='unknown')
      open(lpop+2,file='L',status='unknown')
      open(lpop+3,file='Z',status='unknown')
      open(lpop+4,file='P',status='unknown')

      do i=1,nrbins
         delta=(real(i)-0.5)/real(nrbins)
         area=pi*(real(i)**2.0-real(i-1)**2.0) !only works for 0<r<15+15bins
         write(lpop+1,*)     rmin+(rmax-rmin)*delta,nr(i)/area
      enddo
      do i=1,nlbins
         delta=(real(i)-0.5)/real(nlbins)
         logl=lmin+(lmax-lmin)*delta
         if (nl(i).gt.0) write(lpop+2,*) 10.0**logl,nl(i)
      enddo
      do i=1,nzbins
         delta=(real(i)-0.5)/real(nzbins)
         write(lpop+3,*)     zmin+(zmax-zmin)*delta,nz(i)
      enddo
      do i=1,npbins
         delta=(real(i)-0.5)/real(npbins)
         logp=pmin+(pmax-pmin)*delta
         write(lpop+4,*)     10.0**logp,np(i)
      enddo
      do i=1,4
         close(lpop+i)
      enddo
      end
c==============================================================================
      subroutine bindata(x,xmin,xmax,nbins,nx)
      implicit none
      real x,xmin,xmax,nx(*)
      integer n,nbins
      n=(x-xmin)/(xmax-xmin)*nbins+1
      if (n.ge.1.and.n.le.nbins) nx(n)=nx(n)+1.0
      end
c==============================================================================
      subroutine getmodelranges(filename,lun,xmin,xmax,nx)
      implicit none
      character*(*) filename
      real xmin,xmax,junk
      integer nx,lun

      open(lun,file=filename)
      read(lun,*) xmin,xmax
      nx=0
      do while(.true.)
         read(lun,*,end=999) junk
         nx=nx+1
      enddo
 999  write(*,*) xmin,xmax,nx
      end
c==============================================================================
